name: Publish Docker image

on:
  release:
    types: [published]

env:
  DOCKER_IMAGE_REGISTRY: registry.hub.docker.com
  DOCKER_IMAGE_REPOSITORY: ganex/vsftpd

jobs:
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        id: checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        id: build_publish
        uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ env.DOCKER_IMAGE_REGISTRY }}
          repository: ${{ env.DOCKER_IMAGE_REPOSITORY }}
          auto_tag: true
      - name: Push latest Docker Image
        id: publish_latest
        env:
          TAG: ${{ steps.build_publish.outputs.tag }}
        run: |
          docker tag $TAG ${{ env.DOCKER_IMAGE_REPOSITORY }}:latest
          docker push ${{ env.DOCKER_IMAGE_REPOSITORY }}:latest